In [1]:
import numpy as np
from scipy.stats import t
from scipy.stats import f

Ch03 P.6

In [2]:
mydata = np.loadtxt("/content/drive/MyDrive/Colab Notebooks/3600/ch03/westwood.txt")
x = mydata[:,1:3]
y = mydata[:,3]
n,p=x.shape

In [3]:
ixtx=np.linalg.inv( x.T @ x)
beta=ixtx @ x.T @ y
beta

array([10.,  2.])

P.8

In [4]:
H=x @ ixtx @ x.T

In [5]:
H @ H-H

array([[ 0.00000000e+00,  0.00000000e+00, -6.93889390e-18,
        -2.77555756e-17,  2.77555756e-17,  1.38777878e-17,
        -6.93889390e-18,  0.00000000e+00, -3.46944695e-18,
        -6.93889390e-18],
       [ 0.00000000e+00,  5.55111512e-17, -2.60208521e-17,
        -2.77555756e-17,  2.77555756e-17,  0.00000000e+00,
        -2.60208521e-17,  0.00000000e+00, -2.77555756e-17,
        -2.60208521e-17],
       [ 4.16333634e-17,  3.64291930e-17,  5.55111512e-17,
         5.55111512e-17,  4.16333634e-17,  4.16333634e-17,
         5.55111512e-17,  4.16333634e-17,  2.77555756e-17,
         5.55111512e-17],
       [ 5.55111512e-17,  5.55111512e-17,  8.32667268e-17,
         5.55111512e-17,  6.41847686e-17,  5.55111512e-17,
         8.32667268e-17,  5.55111512e-17,  5.55111512e-17,
         8.32667268e-17],
       [ 2.77555756e-17,  2.77555756e-17,  0.00000000e+00,
         1.73472348e-18,  2.77555756e-17,  1.38777878e-17,
         0.00000000e+00,  2.77555756e-17,  6.93889390e-18,
         0.

In [6]:
IH=np.identity(n)-H

In [7]:
IH @ IH-IH

array([[ 0.00000000e+00, -1.11022302e-16, -1.38777878e-17,
        -2.77555756e-17,  2.77555756e-17,  1.38777878e-17,
        -6.93889390e-18,  0.00000000e+00, -1.04083409e-17,
        -6.93889390e-18],
       [-1.11022302e-16,  1.11022302e-16, -2.60208521e-17,
        -2.77555756e-17,  2.77555756e-17,  0.00000000e+00,
        -2.42861287e-17,  0.00000000e+00, -2.77555756e-17,
        -2.25514052e-17],
       [ 5.55111512e-17,  3.64291930e-17,  1.11022302e-16,
         0.00000000e+00,  4.16333634e-17,  4.16333634e-17,
         2.77555756e-17,  4.16333634e-17,  0.00000000e+00,
         2.77555756e-17],
       [ 6.93889390e-17,  2.77555756e-17,  5.55111512e-17,
         1.11022302e-16,  6.93889390e-17,  8.32667268e-17,
         5.55111512e-17,  5.55111512e-17,  1.11022302e-16,
         8.32667268e-17],
       [ 2.77555756e-17,  2.77555756e-17,  1.38777878e-17,
         1.73472348e-18,  0.00000000e+00, -1.38777878e-17,
         1.38777878e-17,  2.77555756e-17,  6.93889390e-18,
         0.

In [10]:
H @ x - x

array([[-1.11022302e-16, -3.55271368e-15],
       [-3.33066907e-16, -1.42108547e-14],
       [ 4.44089210e-16,  2.13162821e-14],
       [ 4.44089210e-16,  1.42108547e-14],
       [ 0.00000000e+00,  0.00000000e+00],
       [ 4.44089210e-16,  7.10542736e-15],
       [ 4.44089210e-16,  2.13162821e-14],
       [-1.11022302e-16, -3.55271368e-15],
       [ 8.88178420e-16,  5.68434189e-14],
       [ 4.44089210e-16,  2.13162821e-14]])

P.13

In [11]:
yhat=H @ y
yhat

array([ 70.,  50., 130., 170.,  90., 110., 130.,  70., 150., 130.])

In [12]:
res=y-yhat
res

array([ 3.00000000e+00,  2.13162821e-14, -2.00000000e+00, -5.68434189e-14,
       -3.00000000e+00, -2.00000000e+00,  5.00000000e+00, -1.00000000e+00,
       -2.00000000e+00,  2.00000000e+00])

In [13]:
res= IH @ y
res

array([ 3.00000000e+00,  1.77635684e-14, -2.00000000e+00, -4.26325641e-14,
       -3.00000000e+00, -2.00000000e+00,  5.00000000e+00, -1.00000000e+00,
       -2.00000000e+00,  2.00000000e+00])

In [14]:
sse=y @ IH @ y
mse=sse/(n-p)
print(sse)
print(mse)

59.99999999995816
7.49999999999477


P.15

In [15]:
varBeta=mse * ixtx
varBeta

array([[ 6.26470588e+00, -1.10294118e-01],
       [-1.10294118e-01,  2.20588235e-03]])

In [16]:
seBeta=np.sqrt(np.diagonal(varBeta))
seBeta

array([2.50293945, 0.04696682])

In [17]:
myt=t(df=n-p).ppf(0.975)
myt

2.3060041350333704

In [18]:
CI=np.array([beta-myt*seBeta,beta+myt*seBeta])
CI

array([[ 4.22821128,  1.89169431],
       [15.77178872,  2.10830569]])

P.19

In [19]:
x0=np.array([[1,55],
      [1,70]])
yhat=x0 @ beta
yhat

array([120., 150.])

In [20]:
seI=np.sqrt(np.diagonal(x0 @ varBeta @ x0.T+mse))
seI

array([2.8818652 , 3.02197832])

In [21]:
ciI=np.array([yhat-myt*seI, yhat+myt*seI])
ciI

array([[113.35440692, 143.03130551],
       [126.64559308, 156.96869449]])

In [22]:
seM=np.sqrt(np.diagonal( x0 @ varBeta @ x0.T))
seM

array([0.89729987, 1.27763568])

In [23]:
ciM=np.array([yhat-myt*seM, yhat+myt*seM])
ciM

array([[117.93082279, 147.05376683],
       [122.06917721, 152.94623317]])

Ch05 P.7

In [24]:
A=1/n*np.ones((n,n))
A2=H-A
A2

array([[ 1.17647059e-01,  1.76470588e-01, -5.88235294e-02,
        -1.76470588e-01,  5.88235294e-02,  0.00000000e+00,
        -5.88235294e-02,  1.17647059e-01, -1.17647059e-01,
        -5.88235294e-02],
       [ 1.76470588e-01,  2.64705882e-01, -8.82352941e-02,
        -2.64705882e-01,  8.82352941e-02, -1.38777878e-17,
        -8.82352941e-02,  1.76470588e-01, -1.76470588e-01,
        -8.82352941e-02],
       [-5.88235294e-02, -8.82352941e-02,  2.94117647e-02,
         8.82352941e-02, -2.94117647e-02,  2.77555756e-17,
         2.94117647e-02, -5.88235294e-02,  5.88235294e-02,
         2.94117647e-02],
       [-1.76470588e-01, -2.64705882e-01,  8.82352941e-02,
         2.64705882e-01, -8.82352941e-02,  2.77555756e-17,
         8.82352941e-02, -1.76470588e-01,  1.76470588e-01,
         8.82352941e-02],
       [ 5.88235294e-02,  8.82352941e-02, -2.94117647e-02,
        -8.82352941e-02,  2.94117647e-02,  1.38777878e-17,
        -2.94117647e-02,  5.88235294e-02, -5.88235294e-02,
        -2.

In [25]:
ssr=y @ A2 @ y
ssr

13600.00000000004

In [26]:
msr=ssr/(p-1)
msr

13600.00000000004

In [27]:
fRatio=msr/mse
fRatio

1813.3333333346031

In [28]:
f(p-1,n-p).ppf(.95)

5.317655071578714

In [29]:
1-f(p-1,n-p).cdf(fRatio)

1.0195877475638326e-10

In [30]:
sst=np.sum((y-np.mean(y))**2)
rsq=ssr/sst
rsq

0.9956076134699883

In [31]:
mst=sst/(n-1)
adjrsq=1-mse/mst
adjrsq

0.995058565153737